export const EXAM_TYPES = [
  { id: 'thpt',      name: 'Thi THPT Quốc gia', short: 'THPT' },
  { id: 'giua_ky',   name: 'Thi giữa kỳ',       short: 'GK'   },
  { id: 'cuoi_ky',   name: 'Thi cuối kỳ',       short: 'CK'   },
  { id: 'chuyen_de', name: 'Chuyên đề',         short: 'CĐ'   },
  { id: 'khao_sat',  name: 'Khảo sát',          short: 'KS'   },
];

export const EXAM_DIFFICULTY = {
  de:         { label: 'Dễ',        tone: 'easy'    },
  trung_binh: { label: 'Trung bình', tone: 'medium'  },
  kho:        { label: 'Khó',       tone: 'hard'    },
  rat_kho:    { label: 'Rất khó',   tone: 'extreme' },
};

export const EXAM_SUBJECTS = [
  { id: 'toan', name: 'Toán' },
  { id: 'ly',   name: 'Vật lí' },
  { id: 'hoa',  name: 'Hóa học' },
  { id: 'sinh', name: 'Sinh học' },
  { id: 'van',  name: 'Ngữ văn' },
  { id: 'anh',  name: 'Tiếng Anh' },
  { id: 'su',   name: 'Lịch sử' },
  { id: 'dia',  name: 'Địa lí' },
  { id: 'tin',  name: 'Tin học' },
];

export const EXAMS = [
  {
    id: 'thpt-2024-hoa-01',
    title: 'Đề thi THPT Quốc gia 2024 — Hóa học',
    type: 'thpt',
    subject: 'hoa',
    grade: 12,
    year: 2024,
    duration: 50,
    totalQuestions: 3,
    difficulty: 'trung_binh',
    source: 'Bộ GD&ĐT',
    tags: ['chính thức', 'có lời giải'],
    questions: [
      {
        id: 1,
        question: 'Cho 5,6 gam Fe tác dụng với dung dịch HCl dư. Thể tích khí H₂ (đktc) thu được là:',
        options: ['1,12 lít', '2,24 lít', '3,36 lít', '4,48 lít'],
        correct: 1,
        explanation: 'nFe = 5,6/56 = 0,1 mol. Fe + 2HCl → FeCl₂ + H₂. nH₂ = nFe = 0,1 mol. V = 0,1 × 22,4 = 2,24 lít.',
        difficulty: 'de',
        chapter: 'Chương 7: Sắt và hợp chất',
      },
      {
        id: 2,
        question: 'Chất nào sau đây là axit mạnh?',
        options: ['CH₃COOH', 'HCl', 'H₂CO₃', 'H₂S'],
        correct: 1,
        explanation: 'HCl là axit mạnh, phân li hoàn toàn trong nước. Các chất còn lại là axit yếu.',
        difficulty: 'de',
        chapter: 'Chương 1: Sự điện li',
      },
      {
        id: 3,
        question: 'Đốt cháy hoàn toàn 4,4 gam một este no, đơn chức thu được 4,48 lít CO₂ (đktc). CTPT của este là:',
        options: ['C₂H₄O₂', 'C₃H₆O₂', 'C₄H₈O₂', 'C₅H₁₀O₂'],
        correct: 0,
        explanation: 'nCO₂ = 0,2 mol. Este no đơn chức → nH₂O = nCO₂ = 0,2 mol. mC = 2,4; mH = 0,4; mO = 4,4 - 2,4 - 0,4 = 1,6 → nO = 0,1. Tỉ lệ C:H:O = 0,2:0,4:0,1 = 2:4:1. CTPT: C₂H₄O₂ (HCOOCH₃).',
        difficulty: 'trung_binh',
        chapter: 'Chương 1: Este — Lipit',
      },
    ],
    stats: { attempts: 15420, avgScore: 7.2, avgTime: 42, difficulty: 3.5 },
  },
  {
    id: 'giua-ky-1-hoa-11',
    title: 'Đề thi giữa kỳ 1 — Hóa học 11',
    type: 'giua_ky',
    subject: 'hoa',
    grade: 11,
    year: 2024,
    duration: 45,
    totalQuestions: 2,
    difficulty: 'trung_binh',
    source: 'Trường THPT Chuyên',
    tags: ['có đáp án'],
    questions: [
      {
        id: 1,
        question: 'Dung dịch nào sau đây có pH > 7?',
        options: ['NaCl', 'NaOH', 'HCl', 'H₂SO₄'],
        correct: 1,
        explanation: 'NaOH là bazơ mạnh, pH > 7.',
        difficulty: 'de',
      },
      {
        id: 2,
        question: 'Trộn 100 ml dung dịch HCl 0,1M với 100 ml dung dịch NaOH 0,1M. pH của dung dịch sau phản ứng là:',
        options: ['1', '7', '12', '13'],
        correct: 1,
        explanation: 'nHCl = nNaOH = 0,01 mol → phản ứng vừa đủ → dung dịch NaCl trung tính, pH = 7.',
        difficulty: 'trung_binh',
      },
    ],
    stats: { attempts: 3210, avgScore: 6.8, avgTime: 38, difficulty: 3.0 },
  },
  {
    id: 'cuoi-ky-2-toan-10',
    title: 'Đề thi cuối kỳ 2 — Toán 10',
    type: 'cuoi_ky',
    subject: 'toan',
    grade: 10,
    year: 2024,
    duration: 90,
    totalQuestions: 2,
    difficulty: 'kho',
    source: 'Trường THPT Nguyễn Huệ',
    tags: ['tự luận', 'có đáp án'],
    questions: [
      {
        id: 1,
        question: 'Giải bất phương trình: x² − 3x + 2 > 0',
        options: ['x < 1 hoặc x > 2', '1 < x < 2', 'x < 2', 'x > 1'],
        correct: 0,
        explanation: 'x² − 3x + 2 = 0 có nghiệm x = 1, x = 2. Vì a = 1 > 0 nên bất phương trình > 0 khi x < 1 hoặc x > 2.',
        difficulty: 'trung_binh',
      },
      {
        id: 2,
        question: 'Tính sin 30° + cos 60°',
        options: ['0', '0,5', '1', '2'],
        correct: 2,
        explanation: 'sin 30° = 0,5; cos 60° = 0,5. Tổng = 1.',
        difficulty: 'de',
      },
    ],
    stats: { attempts: 5420, avgScore: 6.5, avgTime: 75, difficulty: 3.8 },
  },
  {
    id: 'chuyen-de-ly-12-dao-dong',
    title: 'Chuyên đề Vật lí 12 — Dao động cơ',
    type: 'chuyen_de',
    subject: 'ly',
    grade: 12,
    year: 2024,
    duration: 60,
    totalQuestions: 2,
    difficulty: 'kho',
    source: 'Tài liệu ôn thi',
    tags: ['chuyên đề', 'nâng cao'],
    questions: [
      {
        id: 1,
        question: 'Một con lắc lò xo có chu kỳ T = 2s. Tần số dao động là:',
        options: ['0,5 Hz', '1 Hz', '2 Hz', '4 Hz'],
        correct: 0,
        explanation: 'f = 1/T = 1/2 = 0,5 Hz.',
        difficulty: 'de',
      },
      {
        id: 2,
        question: 'Một vật dao động điều hòa với phương trình x = 5cos(2πt) cm. Vận tốc cực đại của vật là:',
        options: ['5 cm/s', '10 cm/s', '10π cm/s', '5π cm/s'],
        correct: 2,
        explanation: 'v_max = Aω = 5 × 2π = 10π cm/s.',
        difficulty: 'trung_binh',
      },
    ],
    stats: { attempts: 2100, avgScore: 6.8, avgTime: 55, difficulty: 4.0 },
  },
];